pipeline {
    agent any

    environment {
        IMAGE_NAME = "simple-python-app"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                      echo $DOCKER_PASS | docker login \
                        -u $DOCKER_USER --password-stdin
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                  docker build -t $IMAGE_NAME .
                '''
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                  docker stop $IMAGE_NAME || true
                  docker rm $IMAGE_NAME || true
                  docker run -d -p 80:5000 \
                    --name $IMAGE_NAME $IMAGE_NAME
                '''
            }
        }
    }
}
