pipeline {
  agent any
  stages {

    stage('Test') {
      steps {pipeline {
    agent any

    environment {
        IMAGE_NAME = "simple-python-app"

    stages {

        stage('Build Docker Image') 
            steps {
                sh '''
                  docker build -t $IMAGE_NAME:latest .
                '''
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsI: 'docker-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                      echo $DOCKER_PASS | docker login \
                        -u $DOCKER_USER --password-stdin
                    '''
                }
            }
        }

        stage('Push Image') {
            steps {
                sh '''
                  docker tag $IMAGE_NAME:latest \
                    $DOCKER_USER/$IMAGE_NAME:latest

                  docker push $DOCKER_USER/$IMAGE_NAME:latest
                '''
            }
        }

        stage('Deploy Application') {
            steps {
                sh '''
                  docker stop simple-python-app || true
                  docker rm simple-python-app || true

                  docker run -d \
                    --name simple-python-app \
                    -p 80:5000 \
                    $DOCKER_USER/$IMAGE_NAME:latest
                '''
            }
        }
    }
}
        sh 'pip install -r requirements.txt'
      }
    }

    stage('Build Image') {
      steps {
        sh 'docker build -t  .'
      }
    }

    stage('Push Image') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'dockerhub-creds',
          usernameVariable: 'USER',
          passwordVariable: 'PASS'
        )]) {
          sh '''
            echo $PASS | docker login -u $USER --password-stdin
            docker tag simple-python-app $USER/simple-python-app
            docker push $USER/simple-python-app
          '''
        }
      }
    }

    stage('Deploy') {
      steps {
        sh '''
          docker pull $USER/simple-python-app
          docker stop app || true
          docker rm app || true
          docker run -d -p 80:5000 --name app $USER/simple-python-app
        '''
      }
    }
  }

}
